language: java
jdk:
  - oraclejdk8
before_install:
  - mysql -e "create database chat;"
  - mysql -u root -e "CREATE USER chat@localhost IDENTIFIED BY '135792468';"
  - mysql -u root -e "GRANT ALL ON chat.* TO chat@localhost; FLUSH PRIVILEGES;"
  - mysql chat < database.sql
install:
  - mvn install -DskipTests
script:
  - mvn surefire:test
notifications:
  email:
    recipients:
      - lexek-92@ya.ru
    on_success: always
    on_failure: always
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: OLIpYtYqGmhygDpuUBBmTKXS5KneCIPlMUPzd0KC+F0OuOH5Gqhl6IipLuMvAEqxTtI3FWmOpZJDSGWKUCQSWOQEqQFR+i56FHjbCcqwCwTTae1mEcDttTtDZ88NlVWr0J76Hjo3eKfmA2wxh3Tmy7xcOPfuiz/8h3UBPyv9uxPZdqFhftQcB0ZJvAgkFBvr1Tecf9V/FG0onj7lWi/HOVUnvFj0S81ls0TvV6NFsnbEa9P+GLHVEqkMH6/ds8b9zz5FaXKsDWQ8XXpx21DFFfa0UBBBtfWuto/mckyI6d/GIks1vo0FqyuY79oHl1YTVQzeoDSAHtrrfN21iXzPBR9Q1REsyTWkB8zJ32Nq31kCmRylV4GppLVVr1G9hWNc93iPTFbQYAB6irryzUgC/TRp+Ebw+W/ptW01ks4onnacDyjT8uaD392+Wy8ZDQ2BSPaSDwr1BYBagFkgwSITFGmA3JI3m7au08GTg5Sbm1pwfnVWlMIiM2/1+DQ0Gs777hj73W393ibD7oZHhPCu3iEs0AxdxHNSigO40UWgcmne6tY6kYLIjRRSYz/PurmFIF0w07pwVMRxxC9T+6m4tWddOgWLa/hBDQjYiBWJNPx6dZDr4PoZkRdwjcStnV7qhsivogrp8INA44IhTIFO4ND7AawDVWamU5E+MWPtYEA=
  file: target/wschat.jar
  on:
    tags: true
